### ISSUE TITLE
Fails on Windows (only) with ESMOKER_FATAL "PackError: Package manager "npm" failed to pack"

### ISSUE THREAD

**Issue by DavidAnson** [boneskull/midnight-smoker#338]
For example: https://github.com/DavidAnson/markdownlint-cli2/actions/runs/5993175027

The same configuration passes on macOS and Ubuntu. `--verbose` was not enough to expand the nested `cause` object.

```
Run npm exec --yes -- midnight-smoker --verbose test-invoke-as-cli
💨 midnight-smoker v6.1.1
- Packing current project…
✖ Package manager "npm" failed to pack
FatalError: midnight-smoker failed unexpectedly
    at Smoker.smoke (C:\npm\cache\_npx\b66bfc48521ee935\node_modules\midnight-smoker\src\smoker.ts:655:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.handler (C:\npm\cache\_npx\b66bfc48521ee935\node_modules\midnight-smoker\src\cli.ts:423:13) {
  code: 'ESMOKER_FATAL',
  [cause]: {
    error: PackError: Package manager "npm" failed to pack
        at Npm7.pack (C:\npm\cache\_npx\b66bfc48521ee935\node_modules\midnight-smoker\src\pm\npm7.ts:137:13)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at Smoker.pack (C:\npm\cache\_npx\b66bfc48521ee935\node_modules\midnight-smoker\src\smoker.ts:314:20)
        at Smoker.smoke (C:\npm\cache\_npx\b66bfc48521ee935\node_modules\midnight-smoker\src\smoker.ts:618:34)
        at Object.handler (C:\npm\cache\_npx\b66bfc48521ee935\node_modules\midnight-smoker\src\cli.ts:423:13) {
      code: 'ESMOKER_PACK',
      [cause]: [Object]
    }
  }
}
Error: Process completed with exit code 1.
```

**Comment by boneskull** [comment]
@DavidAnson Thanks.  I'll add something that digs further into the `cause`

**Comment by boneskull** [comment]
`--verbose` is broken, lol

**Comment by boneskull** [comment]
See #350 and #351.  Once those are published you should see better error messages.  Then we can see if the pack error is my fault or not. 😄

**Comment by DavidAnson** [comment]
Thanks! Because my test always uses the latest version, you or I can just PR to remove this line to find out once you have published a new version: https://github.com/DavidAnson/markdownlint-cli2/blob/645e69a9c9a88dbe6b5dd912cdd565b8c40579b6/.github/workflows/smoke-test.yml#L37

**Comment by boneskull** [comment]
Please open a new issue if it's obviously a bug in this tool
